name: mercure_client
description: Provide a quick way to publish and consume messages on Mercure
version: 1.1.0
homepage: https://github.com/herveGuigoz/mercure_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3

dev_dependencies:
  test: ^1.16.6
